# Generated by Django 4.0 on 2022-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orm_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yourname', models.CharField(max_length=100, verbose_name='Yourname')),
            ],
        ),
        migrations.DeleteModel(
            name='orm',
        ),
    ]
